[2024-02-16 03:14:13,152: INFO: utils: Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-16 03:14:13,153: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-16 03:14:16,986: WARNING: module_wrapper: From C:\ProgramData\Anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-16 03:14:17,446: INFO: main: >>>>>>>>>> stage Data Ingestion Stage started <<<<<<<<<<]
[2024-02-16 03:14:17,447: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 03:14:17,448: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 03:14:17,450: INFO: common: Created directory at: artifacts]
[2024-02-16 03:14:17,450: INFO: common: Created directory at: data]
[2024-02-16 03:14:17,450: INFO: data_ingestion: Raw data path is - data]
[2024-02-16 03:14:17,450: INFO: main: >>>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<<

X==========X]
[2024-02-16 03:14:17,450: INFO: main: >>>>>>>>>> stage Data Validation stage started <<<<<<<<<<]
[2024-02-16 03:14:17,452: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 03:14:17,452: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 03:14:17,453: INFO: common: Created directory at: artifacts]
[2024-02-16 03:14:17,453: INFO: common: Created directory at: artifacts/ data_validation]
[2024-02-16 03:14:17,453: INFO: main: >>>>>>>>>> stage Data Validation stage completed <<<<<<<<<<

X==========X]
[2024-02-16 03:14:17,454: INFO: main: >>>>>>>>>> stage Data transformation stage started <<<<<<<<<<]
[2024-02-16 03:14:17,455: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 03:14:17,456: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 03:14:17,456: INFO: common: Created directory at: artifacts]
[2024-02-16 03:14:17,456: INFO: common: Created directory at: artifacts/data_transformation]
[2024-02-16 03:14:17,458: INFO: data_transformation: Loaded text data from ******* Sherlock Holmes.txt ******* succcessfully]
[2024-02-16 03:14:17,458: INFO: data_transformation: Tokenizer name set]
[2024-02-16 03:14:17,458: INFO: stage_03_data_transformation: Text data imported]
[2024-02-16 03:14:17,518: INFO: stage_03_data_transformation: Text data tokenize]
[2024-02-16 03:14:17,519: INFO: stage_03_data_transformation: The text data has 8199 word index.]
[2024-02-16 03:14:17,527: INFO: stage_03_data_transformation: Text data has been splited]
[2024-02-16 03:14:17,528: INFO: stage_03_data_transformation: Path: artifacts\data_transformation\Sherlock Holmes.pkl]
[2024-02-16 03:14:17,531: INFO: stage_03_data_transformation: Tokens are saved for Sherlock Holmes]
[2024-02-16 03:14:17,688: ERROR: main: 'Logger' object is not callable]
Traceback (most recent call last):
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\main.py", line 32, in <module>
    data_transformation.main()
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\pipeline\stage_03_data_transformation.py", line 53, in main
    logger(f"The maximum length of Input is {max_len}")
TypeError: 'Logger' object is not callable
