[2024-02-16 02:42:45,733: INFO: utils: Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-16 02:42:45,734: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-16 02:42:50,922: WARNING: module_wrapper: From C:\ProgramData\Anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-16 02:42:51,539: INFO: main: >>>>>>>>>> stage Data Ingestion Stage started <<<<<<<<<<]
[2024-02-16 02:42:51,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 02:42:51,542: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 02:42:51,543: INFO: common: Created directory at: artifacts]
[2024-02-16 02:42:51,544: INFO: common: Created directory at: data]
[2024-02-16 02:42:51,544: INFO: data_ingestion: Raw data path is - data]
[2024-02-16 02:42:51,544: INFO: main: >>>>>>>>>> stage Data Ingestion Stage completed <<<<<<<<<<

X==========X]
[2024-02-16 02:42:51,544: INFO: main: >>>>>>>>>> stage Data Validation stage started <<<<<<<<<<]
[2024-02-16 02:42:51,546: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 02:42:51,547: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 02:42:51,547: INFO: common: Created directory at: artifacts]
[2024-02-16 02:42:51,548: INFO: common: Created directory at: artifacts/ data_validation]
[2024-02-16 02:42:51,548: INFO: main: >>>>>>>>>> stage Data Validation stage completed <<<<<<<<<<

X==========X]
[2024-02-16 02:42:51,549: INFO: main: >>>>>>>>>> stage Data transformation stage started <<<<<<<<<<]
[2024-02-16 02:42:51,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-16 02:42:51,552: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-02-16 02:42:51,552: INFO: common: Created directory at: artifacts]
[2024-02-16 02:42:51,553: INFO: common: Created directory at: artifacts/data_transformation]
[2024-02-16 02:42:51,556: INFO: data_transformation: Loaded text data from ******* Sherlock Holmes.txt ******* succcessfully]
[2024-02-16 02:42:51,556: INFO: data_transformation: Tokenizer name set]
[2024-02-16 02:42:51,557: INFO: stage_03_data_transformation: Text data imported]
[2024-02-16 02:42:51,645: INFO: stage_03_data_transformation: Text data tokenize]
[2024-02-16 02:42:51,645: INFO: stage_03_data_transformation: The text data has 8199 word index.]
[2024-02-16 02:42:51,656: INFO: stage_03_data_transformation: Text data has been splited]
[2024-02-16 02:42:51,657: ERROR: main: 'DataTransformation' object has no attribute 'filename']
Traceback (most recent call last):
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\main.py", line 32, in <module>
    data_transformation.main()
  File "C:\Master's In Mechatronics\Practice\NLP\new_successive_word_suggestion\src\pipeline\stage_03_data_transformation.py", line 33, in main
    token_path = os.path.join(data_transformation.config.data_path, data_transformation.filename)
AttributeError: 'DataTransformation' object has no attribute 'filename'
